name: My Workflow

on:
  repository_dispatch:
    types: [my_event_type]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Parse ServiceNow data
        run: |
          echo "Payload: ${{ toJson(github.event.client_payload) }}"
          echo "Field value: ${{ github.event.client_payload.field_name }}"
