name: Trigger repo (successful)
on:
  - push
  - workflow_dispatch


jobs:
  Repo-Dispatch-calee_repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read repo.json file
        id: read_file
        run: |
          echo "TF_VAR_vault_client_token=$(jq -r '.auth.client_token' repo.json)" >> $GITHUB_ENV
          CONTENT=$(cat payload.json)
          echo ${CONTENT}
          echo "REPO_JSON=='$(jq -r '.' repo.json)"' >> $GITHUB_ENV
        shell: bash

      - name: Repo Dispatch
        id: dispatch
        uses: kabinhamal/repo_dispatch/dispatch@main
        with:
          payload: ${{ env.REPO_JSON }}
          TARGET_REPO: ${{ env.TARGET_REPO }}
          func_token: ${{ secrets.func_token }}
          workflow_id: repo_dispatch1
