name: Trigger repofile
on:
  - push
  - workflow_dispatch

jobs:
  Repo-Dispatch-callee_repo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set REPO_JSON variable
        run: |
          repo=$(cat repo.json)
          echo "REPO_JSON=$repo" >> $GITHUB_ENV
        shell: bash

        

      - name: Repo Dispatch
        id: dispatch
        uses: kabinhamal/repo_dispatch/dispatch@main
        env:
          REPO_JSON: ${{ secrets.REPO_JSON }}
          TARGET_REPO: ${{ secrets.TARGET_REPO }}
          func_token: ${{ secrets.func_token }}
          workflow_id: repo_dispatch1
