name: payload hcl
on:
  - workflow_dispatch
  #- push

env:
  payload: |
    asg5 = {
      env             = "dev" 
      managed_asg     = true
      instance        = "003"
      location        = "EASTUS"
      purpose         = "test"
      additional_tags = {}
    }
  workflow_id: "repo_dispatch1"
  TARGET_REPO: "callee_repo"
     
    

jobs:

    Repo-Dispatch-Hashi_Vault_Secrets_Setup:
        runs-on: ubuntu-latest   
      
        steps: 

          - uses: actions/checkout@v3
              
          - name: Repo Dispatch
            id: dispatch
            uses: kabinhamal/repo_dispatch/dispatch@main
            with:
              payload: ${{ env.payload }}                     
              TARGET_REPO: ${{ env.TARGET_REPO }} 
              func_token: ${{secrets.func_token}}
              workflow_id: ${{ env.workflow_id }} 
              


 
