name: Trigger repo feature (successful)
on:
   # - push  
   -  workflow_dispatch

env:
      payload: '{"newyork": {"env": "dev", "managed_asg": true, "instance": "003", "location": "EASTUS", "purpose": "test", "additional_tags": {}}}'  
      workflow_id: "repo_dispatch"
      TARGET_REPO: "callee_repo"
    

jobs:

    Repo-Dispatch-calee_repo:
        runs-on: ubuntu-latest   
      
        steps: 

          - uses: actions/checkout@v3
              
          - name: Repo Dispatch
            id: dispatch
            uses: kabinhamal/repo_dispatch/dispatch@feature
            with:
              payload: ${{ env.payload }}                     
              TARGET_REPO: ${{ env.TARGET_REPO }} 
              func_token: ${{secrets.func_token}}
              workflow_id: ${{ env.workflow_id }} 
              


 
