name: substitute the value in app.json??

on:
  push:
    branches:
      - featue
env:  
      workflow_id: "repo_dispatch1_feature"
      callee_repo_name:  "callee_repo"
     # WORKSPACE: '["test", "rest"]'
      

jobs:
  sub_env_and_dispatch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set environment variables
        run: |
          echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          echo "PROJECT=Default Project" >> $GITHUB_ENV
        #  echo "WORKSPACE=fedspn" >> $GITHUB_ENV
        
        
      - name: Convert string to list
        id: convert
        run: |
          list_string='["Event Hub", "Azure SQL"]'
          result=$(echo "$list_string" | jq -c .)
          echo "WORKSPACE=\"$result\"" >> $GITHUB_ENV
          
          
      - name: Substitute the env vars in app.json
        shell: bash
        run: |
            source ~/.bash_profile
            envsubst < app.json > tmp.json
            mv tmp.json app.json
            CONTENT=$(cat app.json)
            echo "$CONTENT"
            
            #json_string=$(echo "$CONTENT" | jq -c .)
            #echo "'$json_string'"
            #echo "REPO_JSON='$json_string'" >> $GITHUB_ENV

            
#       - name: Repo Dispatch
#         id: dispatch
#         uses: kabinhamal/repo_dispatch/dispatch1@main
#         with:
#           payload: ${{ env.REPO_JSON }}                     
#           callee_repo_name: ${{ env.callee_repo_name }} 
#           func_token: ${{secrets.func_token}}
#           workflow_id: ${{ env.workflow_id }} 
#           branch: feature

