name: substitute the value in app.json??

on:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set environment variables
        run: |
          echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          echo "PROJECT=Default Project" >> $GITHUB_ENV
          echo "WORKSPACE=fedspn" >> $GITHUB_ENV

      - name: Substitute the env vars in app.json
        shell: bash
        run: |
            source ~/.bash_profile
            envsubst < app.json > tmp.json
            mv tmp.json app.json
            CONTENT=$(cat app.json)
            echo "$CONTENT"
            json_string=$(echo "$CONTENT" | jq -c .)
            echo "'$json_string'"
            echo "REPO_JSON='$json_string'" >> $GITHUB_ENV

