name: substitute the value in app.json??

on:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        run: |
          echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          echo "PROJECT=Default Project" >> $GITHUB_ENV
          echo "WORKSPACE=fedspn" >> $GITHUB_ENV

      - name: Render Helm Chart
        shell: bash
        run: |
            source ~/.bash_profile
            envsubst < app.yaml > tmp.yaml
            mv tmp.yaml app.yaml
